version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Your_Strong_Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql/data
